### ISSUE TITLE
Fail to run "hugo server"

### ISSUE THREAD

**Issue by ghost** [ntk148v/hugo-toigian#1]
$ hugo server -DF --disableFastRender
Start building sites …
hugo v0.105.0-0e3b42b4a9bdeb4d866210819fc6ddcf51582ffa+extended darwin/amd64 BuildDate=2022-10-28T12:29:05Z VendorInfo=gohugoio
ERROR 2022/11/17 14:05:04 POSTCSS: failed to transform "css/light.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
ERROR 2022/11/17 14:05:04 POSTCSS: failed to transform "css/dark.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Error: Error building site: POSTCSS: failed to transform "css/toigian.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Built in 4118 ms

**Comment by ntk148v** [comment]
Hi @Miraboreas, did you run `npm install` in order to install postcss, postcss-cli, tailwindcss?

I've updated README to remind it.

**Comment by Miraboreas** [comment]
Yeah, before I open this issue I've run`npm install`.
Just now I moved "resources" in example to my root directory, it works😂

**Comment by ghost** [comment]
Yeah, before I open this issue I've runnpm install.
Just now I moved "exampleSite/resources" to my root directory, it works😂
I don't know what happened.
