### ISSUE TITLE
Failed to find 'tailwindcss/base' in css/toigian.css

### ISSUE THREAD

**Issue by chienduynguyen1702** [ntk148v/hugo-toigian#2]
![image_2022-12-28_011442659](https://user-images.githubusercontent.com/96042873/209706236-f0841757-c955-4be9-8be5-121c0a17156c.png)
![image](https://user-images.githubusercontent.com/96042873/209706362-9b6fa2d0-e352-4ef9-9c40-4ac2da94af05.png)

im a beginner, im so confused that i do not see any file named ```tailwindcss/base```, can you show me something is wrong there ? 
Vietnamese is oke :v

**Comment by ntk148v** [comment]
@ChienDuyNguyen1702 Did you try to run `npm install` in themes/hugo-toigian? Or you can install tailwindcss with `npm install -D tailwindcss` 🥂 

> Vietnamese is oke?

Đương nhiên rồi 🇻🇳

**Comment by chienduynguyen1702** [comment]
thanks alot, its work
