### ISSUE TITLE
Date not formatting on deployment via netlify?

### ISSUE THREAD

**Issue by keaan95** [ntk148v/hugo-toigian#3]
Hi Kien, many thanks for theme. Working really well.

Unfortunately, the date seems not to be formatting on netlify deployment - www.doctorx.co.uk is my example.

Any help with this would be greatly appreciated.

**Comment by keaan95** [comment]
Corrected hugo version to match upload. Fixed.

Thanks once more. Terrific theme.

**Comment by ntk148v** [comment]
@keaan95 I'm glad you love it! Have a nice day!
